service: norskecasino-casino-serverless

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    packager: 'yarn'
    packagerOptions: {}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  environment:
    STAGE: ${self:custom.stage}

functions:
  fn1:
    handler: src/handler.fn1
    events:
      - http:
          path: fn1
          method: get

